### ISSUE TITLE
build: PackPluginZip is non-incremental and consumed via a hard-coded bin path — latent CS1566 parallel-build race

### ISSUE THREAD

**Issue by NBoztepe** [MrNedimBoztepe/Shonkor#350]
Reported by the developer during #312 (pre-existing, not introduced by PR #347) and confirmed by the architecture review.

## Symptom
A parallel `dotnet build` / `dotnet test` intermittently fails with:
```
CSC : error CS1566: … Shonkor.Plugin.TypeScript.zip … used by another process
```
Reproduced twice in a row during #312; `-m:1` works around it. CI currently runs without `-m:1` (.github/workflows/ci.yml:68, bench.yml:43,74) and is green — the race is **latent, not chronic**, but it is exactly the kind of flake that appears under load.

## Root cause (not incidental)
`src/Shonkor.Infrastructure/Shonkor.Infrastructure.csproj:25` consumes **another project's build output as a compile input**, via a hard-coded `..\Shonkor.Plugin.TypeScript\bin\$(Configuration)\net10.0\…zip` path — i.e. outside MSBuild's dependency graph. The producer `PackPluginZip` (Shonkor.Plugin.TypeScript.csproj:116) is **not incremental** (no `Inputs`/`Outputs`) and does `Delete` + `ZipDirectory` on that exact file on *every* build. If the plugin project is re-entered while `csc` holds the ZIP as an `EmbeddedResource` → CS1566.

The same hard-coded bin-path pattern also exists in `tests/Shonkor.Tests/Shonkor.Tests.csproj` (`_TsPluginOut`) — it is systemic, not a one-off.

## Acceptance Criteria
- [ ] `PackPluginZip` is incremental (`Inputs`/`Outputs`), so an unchanged plugin output no longer deletes and rewrites the ZIP.
- [ ] A parallel build (`dotnet build` without `-m:1`, repeated) no longer reproduces CS1566.
- [ ] (Optional, cleaner) the ZIP is passed to Infrastructure via a `Returns` target of the plugin project instead of a bin path, putting the dependency into the graph.

## Why now
Every further plugin (the PHP family is next) will copy this pattern. Fixing the producer before it is duplicated is cheaper than fixing N copies.

## Context
- src/Shonkor.Infrastructure/Shonkor.Infrastructure.csproj:25 — consumer, hard-coded bin path
- src/Shonkor.Plugin.TypeScript/Shonkor.Plugin.TypeScript.csproj:116 — non-incremental producer
- tests/Shonkor.Tests/Shonkor.Tests.csproj — same pattern (`_TsPluginOut`)
- Origin: #312 / PR #347
